server:
  port: 8787
spring:
    application:
      name: crud

    r2dbc:
      url: r2dbc:postgresql://localhost:5432/crud_reactive
      username: postgres
      password: postgres

    datasource:
      url: jdbc:postgresql://localhost:5432/crud_reactive
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver

    flyway:
      locations: classpath:db/migration
