server:
  port: 8012
spring:
  application:
    name: common
  datasource:
    url: jdbc:postgresql://localhost:5240/common
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect